### ISSUE TITLE
OpenGL - why no? 

### ISSUE THREAD

**Issue by ghost** [a2flo/floor#1]
Hello. Why there is no OpenGL backend? 
OpenGL have many required extensions.

**Comment by a2flo** [comment]
a) there is OpenGL interop support for the CUDA, OpenCL and Host-Compute backends
b) how exactly would that work in the first place? I might be able to get something like SPIRV-Cross to convert SPIR-V back to GLSL that OpenGL might be able to understand, but right now it's already hard enough to generate SPIR-V that Vulkan can understand. Supporting OpenGL, which is far less capable, would be even harder or impossible for certain features.
c) OpenGL is dead anyways at this point, use Vulkan or Metal when you need graphics, use OpenCL or CUDA when you need compute

**Comment by ghost** [comment]
Also, we have DirectX 12. Why there is no DirectX 12?

**Comment by a2flo** [comment]
You do realize that adding any kind of new backend requires a considerable amount of work, right?
That being said, I might actually add a DirectX 12 backend once Microsoft releases their new LLVM HLSL compiler and LLVM-based shader format, which I can hopefully target.

**Comment by a2flo** [comment]
- closing this, OpenGL support will be removed after the v0.3 release, DirectX is not happening
