### ISSUE TITLE
newComputePipelineStateWithFunction failed

### ISSUE THREAD

**Issue by hanjin666** [a2flo/floor#2]
I compiled a very simple metallib kernel  and load it.when invoke newComputePipelineStateWithFunction ,console report "XPC_ERROR_CONNECTION_INTERRUPTED" on create metal_program. can you help me analyze the problem?thanks.

**Comment by a2flo** [comment]
Hi, what exactly are you trying to do? Which OS/version are you using? What is your kernel code?

**Comment by hanjin666** [comment]
macOSX 10.13.6,kernel code very simple,like `kernel void helloWorld(){}  `, kernel has be compiled to a metallib file . in our projection, llvm and clang linked be a third-party library,not as command line tools.
`          NSError *err = nullptr;`
         ` id<MTLComputePipelineState> kernel_state = nil;`
       `   if ([func functionType] == MTLFunctionTypeKernel) {`
           ` auto dev = [prog.second.program device];`
          `  kernel_state = [dev  newComputePipelineStateWithFunction:func  error:&err];`
      `      if (!kernel_state) {`
           `   log_error(`
               `   "failed to create kernel state \"%s\" for device \"%s\": %s",`
          `        info.name, prog.first->name,`
       `           (err != nullptr ? [[err localizedDescription] UTF8String]`
         `                         : "unknown error"));`
      `        continue;`
       `     }`
      `    }`
failed to create kernel state.

**Comment by a2flo** [comment]
Can you upload the metallib file? Also, which GPU?
This error usually occurs when the compiler service / backend compiler crashes.

**Comment by hanjin666** [comment]
[temp_file_or_code.metallib.zip](https://github.com/a2flo/floor/files/2938980/temp_file_or_code.metallib.zip)
hi,thx for your response .graphic card is gtx750ti.

kernel's source code
`#include <common.hh>`
`#include <flywave/math/color.hh>`

`void test1(global flywave::color4<float> *cay, global int *size) {`
`  int gid = get_group_id(0);`
  `int glbid = get_global_id(0);`
 ` int lid = get_local_id(0);`

 ` int gsize = get_group_size(0);`
 ` int gblsize = get_global_size(0);`
  `int lsize = get_local_size(0);`

  i`nt index = glbid + lid;`
  `barrier();`

 ` if (index >= *size)`
   ` return;`

  `auto &d = cay[index];`
`  auto aver = (d.r * 0.3 + d.g * 0.59 + d.b * 0.11);`
  `d.r = aver;`
 ` d.g = aver;`
 ` d.b = aver;`
`}`

`kernel void helloWorld(global int *size) {`
`#if !defined(FLYWAVE_COMPUTE_METAL)`
 ` printf("hello world! %d \n", *size);`
`#endif`
`}`

`kernel void helloWorld1(global flywave::color4<float> *data, global int *size) {`
  `test1(data, size);`
`}`

**Comment by a2flo** [comment]
Hm, probably shouldn't use doubles.
Other than that, there might be other Nvidia backend compiler issues on 10.13.

**Comment by hanjin666** [comment]
thanks,I got it.cuda do not work on this computer .once invoke cuda's api,then application will be crashed.there might be a Nvidia  webdriver's bug.

**Comment by a2flo** [comment]
- closing this, since it's outdated
